USE QL_DH_GH
GO

--DROP PROC Sp_DangNhap
--DROP PROC Sp_NV_DuyetHopDong

-- Xử lí đăng nhập tài khoản
CREATE PROC Sp_DangNhap
	@TENDANGNHAP VARCHAR(50),
	@MATKHAU VARCHAR(50),
	@MAACC VARCHAR(15) OUTPUT,
	@LOAIACC INT OUTPUT
AS
BEGIN
	SET @MAACC = 'NULL'
	IF NOT EXISTS (SELECT MAACC
				FROM ACCOUNT 
				WHERE TENDANGNHAP = @TENDANGNHAP 
				AND MATKHAU = @MATKHAU)
	BEGIN
		PRINT N'Sai tên đăng nhập hoặc mật khẩu'
		RETURN 0
	END
	
	-- lấy mã acc
	SET @MAACC = (SELECT MAACC
				FROM ACCOUNT
				WHERE TENDANGNHAP = @TENDANGNHAP
				AND MATKHAU = @MATKHAU)

	-- lấy loại acc
	SET @LOAIACC = (SELECT LOAIACC
				FROM ACCOUNT
				WHERE TENDANGNHAP = @TENDANGNHAP
				AND MATKHAU = @MATKHAU)

	-- xử lí đăng nhập
	if (@MAACC != 'NULL')
	BEGIN
		PRINT N'Đăng nhập thành công'
		RETURN 1
	END
	ELSE RETURN 0	
END
GO

--------------------PROCEDURE-PHẦN CỦA ĐỨC

-- Nhân viên duyệt hợp đồng
CREATE 
PROC Sp_NV_DuyetHopDong
	@NGAYBATDAU DATE,
	@NGAYKETTHUC DATE,
	@MANV VARCHAR(15),
	@MAHD VARCHAR(15)	
AS
BEGIN
	--kiểm tra mã hợp đồng có tồn tại hay không
	IF NOT EXISTS (SELECT MAHD 
				FROM HOPDONG 
				WHERE MAHD = @MAHD )
	BEGIN
		PRINT CAST(@MAHD AS VARCHAR(15)) + N' Không Tồn Tại'
		RETURN 0
	END

	--kiểm tra mã nhân viên có tồn tại hay không
	IF NOT EXISTS (SELECT MANV
				FROM NHANVIEN
				WHERE MANV = @MANV )
	BEGIN
		PRINT CAST(@MANV AS VARCHAR(15)) + N' Không Tồn Tại'
		RETURN 0
	END

	-- duyệt hợp đồng
	UPDATE HOPDONG
	SET DADUYET = 1, NGAYBATDAU = @NGAYBATDAU, NGAYKETTHUC = @NGAYKETTHUC, MANV = @MANV
	WHERE MAHD = @MAHD 	
	RETURN 1
END
GO

-- Nhân viên loại bỏ hợp đồng (không duyệt hợp đồng)
CREATE 
PROC Sp_NV_LoaiBoHopDong
	@NGAYBATDAU DATE,
	@NGAYKETTHUC DATE,
	@MANV VARCHAR(15),
	@MAHD VARCHAR(15)
AS
BEGIN
	--kiểm tra mã hợp đồng có tồn tại hay không
	IF NOT EXISTS (SELECT * 
				FROM HOPDONG 
				WHERE MAHD = @MAHD )
	BEGIN
		PRINT CAST(@MAHD AS VARCHAR(15)) + N' Không Tồn Tại'
		RETURN 0
	END

	--kiểm tra mã nhân viên có tồn tại hay không
	IF NOT EXISTS (SELECT * 
				FROM NHANVIEN
				WHERE MANV = @MANV )
	BEGIN
		PRINT CAST(@MANV AS VARCHAR(15)) + N' Không Tồn Tại'
		RETURN 0
	END

	-- loại bỏ hợp đồng
	UPDATE HOPDONG
	SET DADUYET = 2, MANV = @MANV
	WHERE MAHD = @MAHD 	
	RETURN 1
END
GO

--Đổi mật khẩu tài khoản nhân viên
CREATE PROC Sp_NV_DoiMatKhau
	@MANV VARCHAR(15),
	@MATKHAU VARCHAR(50)
AS
BEGIN
	--kiểm tra mã nhân viên có tồn tại hay không
	IF NOT EXISTS (SELECT * 
				FROM NHANVIEN
				WHERE MANV = @MANV )
	BEGIN
		PRINT CAST(@MANV AS VARCHAR(15)) + N' Không Tồn Tại'
		RETURN 0
	END

	-- lấy MAACC
	DECLARE @MAACC VARCHAR(15)
	SET @MAACC = (SELECT MAACC
				FROM NHANVIEN
				WHERE MANV = @MANV)

	-- xử lí Update mật khẩu
	UPDATE ACCOUNT
	SET MATKHAU = @MATKHAU 
	WHERE MAACC = @MAACC	
	RETURN 1
END
GO
























---- Đối tác lấy số lượng tất cả đơn hàng
--CREATE PROC Sp_DT_LayTatCaDonHang
--	@MADT VARCHAR(15), 
--	@TATCA_DH1 VARCHAR(15) OUTPUT, 
--	@TATCA_DH2 VARCHAR(15) OUTPUT
--AS
--BEGIN
--	SET @TATCA_DH1 = '0'
--	SET @TATCA_DH2 = '0'
--	IF NOT EXISTS (SELECT * 
--				FROM DOITAC
--				WHERE MADT = @MADT) 			
--	BEGIN
--		PRINT CAST(@MADT AS VARCHAR(15)) + N' Không Tồn Tại'
--		RETURN 0
--	END
	
--	-- xử lí lấy số lượng tất cả đơn hàng lần 1	
--	SET @TATCA_DH1 = (SELECT COUNT(*)
--				FROM DONHANG
--				WHERE MADT = @MADT
--				GROUP BY MADT)

--	-- xử lí lấy số lượng tất cả đơn hàng lần 2	
--	SET @TATCA_DH2 = (SELECT COUNT(*)
--				FROM DONHANG
--				WHERE MADT = @MADT
--				GROUP BY MADT)
--RETURN 1
--END 
--GO

---- Khách hàng thêm đơn hàng mới
--CREATE PROC Sp_KH_ThemDonHang
--	@MADH VARCHAR(15),
--	@MADT VARCHAR(15),
--	@MAKH VARCHAR(15),
--	@SOLUONGSP INT,
--	@HINHTHUCTHANHTOAN INT,
--	@DIACHIGH NVARCHAR(50),
--	@NGAYLAP DATETIME,
--	@TONGPHISP DECIMAL(19,4),
--	@PHIVANCHUYEN DECIMAL(19,4),
--	@TONGPHI DECIMAL(19,4) ,
--	@TINHTRANG INT
--AS
--BEGIN	
--	IF NOT EXISTS (SELECT * 
--				FROM DOITAC
--				WHERE MADT = @MADT) 			
--	BEGIN
--		PRINT CAST(@MADT AS VARCHAR(15)) + N' Không Tồn Tại'
--		RETURN 0
--	END

--	IF NOT EXISTS (SELECT * 
--				FROM KHACHHANG
--				WHERE MAKH = @MAKH) 			
--	BEGIN
--		PRINT CAST(@MAKH AS VARCHAR(15)) + N' Không Tồn Tại'
--		RETURN 0
--	END
	
--	-- xử lí thêm đơn hàng
--	INSERT INTO DONHANG(MADH,MADT,MAKH,SOLUONGSP,HINHTHUCTHANHTOAN, DIACHIGH, NGAYLAP, TONGPHISP, PHIVANCHUYEN, TONGPHI, TINHTRANG)
--	VALUES
--		(@MADH,@MADT,@MAKH,@SOLUONGSP,@HINHTHUCTHANHTOAN, @DIACHIGH, @NGAYLAP, @TONGPHISP, @PHIVANCHUYEN, @TONGPHI, @TINHTRANG)
--	RETURN 1
--END
--GO

---- Khách hàng thêm chi tiết đơn hàng
--CREATE PROC Sp_KH_ThemCT_DonHang
--	@MADT VARCHAR(15),
--	@MADH VARCHAR(15),	
--	@MASP VARCHAR(15),
--	@SOLUONG INT,	
--	@THANHTIEN DECIMAL(19,4)
--AS
--BEGIN	
--	IF NOT EXISTS (SELECT * 
--				FROM DOITAC
--				WHERE MADT = @MADT) 			
--	BEGIN
--		PRINT CAST(@MADT AS VARCHAR(15)) + N' Không Tồn Tại'
--		RETURN 0
--	END

--	IF NOT EXISTS (SELECT * 
--				FROM DONHANG
--				WHERE MADH = @MADH) 			
--	BEGIN
--		PRINT CAST(@MADH AS VARCHAR(15)) + N' Không Tồn Tại'
--		RETURN 0
--	END

--	IF NOT EXISTS (SELECT * 
--				FROM SANPHAM
--				WHERE MASP = @MASP) 			
--	BEGIN
--		PRINT CAST(@MASP AS VARCHAR(15)) + N' Không Tồn Tại'
--		RETURN 0
--	END

--	-- xử lí thêm chi tiết đơn hàng
--	INSERT INTO CT_DONHANG(MADT,MADH,MASP,SOLUONG,THANHTIEN)
--	VALUES
--		(@MADT,@MADH,@MASP,@SOLUONG,@THANHTIEN)
--	RETURN 1
--END
--GO

---- Khách hàng thêm xử lí đơn hàng
--CREATE PROC Sp_KH_ThemXULI_DONHANG	
--	@MADH VARCHAR(15),	
--	@MATX VARCHAR(15),
--	@NGAYTXNHAN DATE,
--	@NGAYKHNHAN DATE
--AS
--BEGIN	
--	IF NOT EXISTS (SELECT * 
--				FROM DONHANG
--				WHERE MADH = @MADH) 			
--	BEGIN
--		PRINT CAST(@MADH AS VARCHAR(15)) + N' Không Tồn Tại'
--		RETURN 0
--	END

--	IF NOT EXISTS (SELECT * 
--				FROM TAIXE
--				WHERE MATX = @MATX) 			
--	BEGIN
--		PRINT CAST(@MATX AS VARCHAR(15)) + N' Không Tồn Tại'
--		RETURN 0
--	END

--	-- xử lí thêm chi tiết đơn hàng
--	INSERT INTO XULI_DONHANG(MADH,MATX,NGAYTXNHAN,NGAYKHNHAN)
--	VALUES
--		(@MADH,@MATX,@NGAYTXNHAN,@NGAYKHNHAN)
--	RETURN 1
--END
--GO
