--USE QL_DH_GH
--GO

SELECT * FROM HOPDONG

DECLARE @RT INT
EXEC @RT = Sp_NV_DuyetHopDong2 'NV111', 'HD111'
IF @RT = 0
	PRINT N'DUYỆT HỢP ĐỒNG THẤT BẠI'
ELSE
	PRINT N'DUYỆT HỢP ĐỒNG THÀNH CÔNG'

SELECT * FROM HOPDONG