-- Đối tác cập nhật giá sản phẩm
-- Transaction 1
CREATE 
PROC Sp_DT_UPDATE_GiASP
	@MASP VARCHAR(15),
	@MADT VARCHAR(15),
	@GIAMOI DECIMAL(19,4)
AS
BEGIN TRAN
	BEGIN TRY
		IF NOT EXISTS(SELECT *
					FROM SANPHAM
					WHERE MASP = @MASP AND MADT = @MADT)
		BEGIN
			PRINT N'SẢN PHẨM KHÔNG TỒN TẠI'
			ROLLBACK TRAN
			RETURN 1
		END
		
		UPDATE SANPHAM
		SET GIABAN = @GIAMOI
		WHERE MASP = @MASP AND MADT= @MADT 

		--ĐỂ TEST
		WAITFOR DELAY '0:0:20'

		IF @GIAMOI = 0
		BEGIN
			ROLLBACK TRAN 
			RETURN 1
		END
		-----
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0
GO

-- Khach hang xem san pham cua mot doi tac
-- Transaction 2
CREATE 
PROC Sp_KH_XEMSP
	@MADT VARCHAR(15)
AS
--SET TRAN ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
	BEGIN TRY
		SELECT  SP.TENSP, SP.SOLUONG, SP.GIABAN, CN.DIACHI, SP.MASP 
                FROM SANPHAM SP, CHINHANH CN
                WHERE SP.CHINHANH = CN.MACHINHANH
                AND SP.MADT = CN.MADT
                AND SP.MADT = @MADT
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
	END CATCH
COMMIT TRAN
GO